### PR TITLE
Deleted Tornado

### PR DESCRIPTION
**Pull request by agrymaloski**
Deleted tornado, routes and handlers.

### CODE REVIEW

**Comment by dragonprevost** [comment]
Hey make sure you pushed the commit where you deleted all the routes and handler files, I dont think I see them in this pull request...

Other than that everything is looking really good! Just let me know once you push again!

**Comment by agrymaloski** [comment]
Re-tried to upload code. Should work?

**Comment by dragonprevost** [comment]
> Re-tried to upload code. Should work?
Looks like it is on there! I will take a look at everything now.

**Comment by dragonprevost** [comment]
> Looking good to me!
> 
> I did notice that we didn't remove `tornado` from `requirements.txt`. I tried removing it and it appears that the `asyncio` package was bundled inside of tornado, and we're still using it in a few areas of the code. @dragonprevost Maybe we can go ahead with a merge on this one, and remove the tornado dependency in a subsequent PR?

Yeah sounds good to me, it seems that there may be some deeper digging into the async situation but that is outside the scope of this Issue...

**Pull request merged**
